spring:
  application:
    name: petkoc

  config:
    location: src/main/resources
    name: application.yml

  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: ENC(mMAuUmuApYJDCqmDsphoYLEQXDn/o7lSY3dqJsrxytPQYc/UNBOCKA==)
    password: ENC(8ZnY5WHjA36qwOEQRFdnEXUdbBT14iLZ)
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      allow-pool-suspension: true
      max-lifetime: 30000
      connection-timeout: 100000


  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: Naver
            client-id: ENC(1aEkksbBqcAZbSxUIS4z8ZYieLGNBb/ViN2+P6VhaHE=)
            client-secret: ENC(dt7D9AATXy8AlM/Sg5uRS6thsNlTmXBK)
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - email
          kakao:
            client-name: Kakao
            client-id: ENC(ObSnoZZsj8WgqjjVbqrKPpl8zz/9Zfgt/YAgrqGTjs8FTbz6Vm/zuh2iytVpLR8A)
            client-secret: ENC(BtpMiOZBvYQapeBfil55jLRAWdA+xrzcfx9I/8YcG4+Z1944hOYYHxP8Wo7U2bJY)
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl_auto: update
    generate-ddl: false

  jwt:
    header: Authorization
    secret: ENC(+OElkuP00E4MdnviN0TurtqpWOzintkCs0waFEDAm9DLnR4cNXhrqLxdFEI4e0bj/oHBFSZMLEYhwl6YlPz42/w9D3uVth2OJZCpPMj2++w=)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

logging:
  level:
    org:
      jasypt: debug
      springframework.security: debug
    com.dog.petkoc.*: DEBUG
