spring:
  application:
    name: petkoc

  config:
    location: src/main/resources
    name: application.yml

  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: ENC(mMAuUmuApYJDCqmDsphoYLEQXDn/o7lSY3dqJsrxytPQYc/UNBOCKA==)
    password: ENC(8ZnY5WHjA36qwOEQRFdnEXUdbBT14iLZ)
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      allow-pool-suspension: true
      max-lifetime: 30000
      connection-timeout: 100000


  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: NAVER
            client-id: ENC(1aEkksbBqcAZbSxUIS4z8ZYieLGNBb/ViN2+P6VhaHE=)
            client-secret: ENC(dt7D9AATXy8AlM/Sg5uRS6thsNlTmXBK)
            authorization-grant-type: authorization-code
            redirect-uri: http://localhost:8080/oauth2/code/naver
            scope:
              - name
              - email
              - nickname
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://nid.naver.com/v1/nid/me
            user-name-attribute: response
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl_auto: update
    generate-ddl: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

logging:
  level:
    org:
      jasypt: debug
    com.dog.petkoc.service: DEBUG
